# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vaishali Thakkar
email: me@vaishalithakkar.com
description: Freelance Linux Kernel Hacker and FOSS Program manager
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vaishalithakkar.in" # the base hostname & protocol for your site
twitter_username: kernel_girl
github_username:  nerdyvaishali
linkedin_username: vaishali-thakkar-411b3390
paginate: 5
paginate_path: "blog/page:num/"
theme-dark: false #Set to true to change to dark website theme

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
